insert into colores_sistema (id)
values (1)
on duplicate key update id=id;

insert into cat_tipos_ingreso (nombre,
                               descripcion,
                               es_periodico,
                               frecuencia_dias,
                               mes_pago_tentativo,
                               dia_pago_tentativo,
                               activo)
VALUES ('Nomina',
        'Ingreso por concepto de nómina',
        true,
        15,
        null,
        null,
        true),
       ('DIA SERVIDOR PUBLICO',
        'Día del Servidor Público (conmemoración)',
        false,
        null,
        6,
        30,
        true),
       ('DIA DEL PADRE',
        'Día del Padre (tercer domingo de junio) — 2026: 21/jun',
        false,
        null,
        6,
        21,
        true),
       ('DIA DE LA MADRE',
        'Día de la Madre — 2026: 10/may',
        false,
        null,
        5,
        10,
        true),
       ('DIA DEL MAESTRO',
        'Día del Maestro — 2026: 15/may',
        false,
        null,
        5,
        15,
        true),
       ('Prima Vacacional 12 Dias, 1ER. Periodo',
        'Prima vacacional — primer periodo (fecha recomendada)',
        false,
        null,
        6,
        1,
        true),
       ('RETROACTIVO',
        'Pago retroactivo',
        false,
        null,
        null,
        null,
        true),
       ('Aguinaldo 40 Dias',
        'Aguinaldo (pago anual) — fecha límite legal en México: 20/dic',
        false,
        null,
        12,
        20,
        true),
       ('Prima Vacacional 12 Dias, 2do. Periodo',
        'Prima vacacional — segundo periodo (fecha recomendada)',
        false,
        null,
        12,
        1,
        true),
       ('Bono Navideno',
        'Bono navideño anual (fecha recomendada)',
        false,
        null,
        12,
        15,
        true),
       ('Ajuste al Calendario 5 Dias',
        'Ajuste al calendario (5 días) — aplicado fin de año',
        false,
        null,
        12,
        31,
        true),
       ('9 DIAS Otras Prestaciones de Fin de Ano',
        'Otras prestaciones de fin de año (9 días) — recomendada en dic',
        false,
        null,
        12,
        20,
        true),
       ('5 DIAS Complemento al Aguinaldo',
        'Complemento al aguinaldo (5 días) — recomendada en dic',
        false,
        null,
        12,
        20,
        true);
