insert into system_colors (id)
values (1);

insert into cat_income_types (name,
                              description,
                              is_periodic,
                              frequency_days,
                              tentative_payment_month,
                              tentative_payment_day,
                              active)
VALUES ('Nomina',
        'Ingreso por concepto de nómina',
        true,
        15,
        null,
        15,
        true),
       ('DIA SERVIDOR PUBLICO',
        'Día del Servidor Público (conmemoración)',
        false,
        null,
        6,
        30,
        true),
       ('DIA DEL PADRE',
        'Día del Padre (tercer domingo de junio) — 2026: 21/jun',
        false,
        null,
        6,
        21,
        true),
       ('DIA DE LA MADRE',
        'Día de la Madre — 2026: 10/may',
        false,
        null,
        5,
        10,
        true),
       ('DIA DEL MAESTRO',
        'Día del Maestro — 2026: 15/may',
        false,
        null,
        5,
        15,
        true),
       ('Prima Vacacional 12 Dias, 1ER. Periodo',
        'Prima vacacional — primer periodo (fecha recomendada)',
        false,
        null,
        6,
        1,
        true),
       ('RETROACTIVO',
        'Pago retroactivo',
        false,
        null,
        null,
        null,
        true),
       ('Aguinaldo 40 Dias',
        'Aguinaldo (pago anual) — fecha límite legal en México: 20/dic',
        false,
        null,
        12,
        20,
        true),
       ('Prima Vacacional 12 Dias, 2do. Periodo',
        'Prima vacacional — segundo periodo (fecha recomendada)',
        false,
        null,
        12,
        1,
        true),
       ('Bono Navideno',
        'Bono navideño anual (fecha recomendada)',
        false,
        null,
        12,
        15,
        true),
       ('Ajuste al Calendario 5 Dias',
        'Ajuste al calendario (5 días) — aplicado fin de año',
        false,
        null,
        12,
        31,
        true),
       ('9 DIAS Otras Prestaciones de Fin de Ano',
        'Otras prestaciones de fin de año (9 días) — recomendada en dic',
        false,
        null,
        12,
        20,
        true),
       ('5 DIAS Complemento al Aguinaldo',
        'Complemento al aguinaldo (5 días) — recomendada en dic',
        false,
        null,
        12,
        20,
        true);


INSERT INTO transaction_categories (name, type, description, contribution_category)
VALUES ('Cuota Ordinaria', 'income', 'Descuento quincenal aplicado por el patrón a agremiados activos.', 'ordinary'),
       ('Cuota Extraordinaria', 'income', 'Aportaciones adicionales autorizadas por la asamblea o comité.', 'extraordinary'),
       ('Aportación Personal de Confianza', 'income', 'Transferencia voluntaria de personal de confianza.', 'trust_staff'),
       ('Cuota Personal Jubilado', 'income', 'Aportación voluntaria de personal jubilado.', 'retired'),
       ('Cuota de Permiso Sindical', 'income', 'Aportación de agremiados con permiso sindical.', 'union_leave'),
       ('Otros ingresos', 'income', 'Ingresos no clasificados en cuotas estándar.', 'other'),
       ('Servicios jurídicos', 'expense', 'Pago de asesoría y representación legal del sindicato.', NULL),
       ('Aportación SNES', 'expense', 'Cuota o aportación institucional al SNES.', NULL),
       ('Mantenimiento de oficina', 'expense', 'Limpieza, reparaciones y mantenimiento general de oficina.', NULL),
       ('Apoyos de solidaridad', 'expense', 'Apoyos por enfermedad, fallecimiento u otras contingencias.', NULL),
       ('Eventos sindicales', 'expense', 'Gastos de convivencias y actividades institucionales.', NULL),
       ('Otros gastos', 'expense', 'Egresos no clasificados en categorías predefinidas.', NULL);


-- Tipos de solicitud
INSERT INTO request_types (name, description, active)
VALUES ('Lentes', 'Solicitud de apoyo para adquisición de lentes oftálmicos.', TRUE),
       ('Laptop', 'Solicitud de apoyo para adquisición de equipo de cómputo portátil.', TRUE);
