name: 🚀 Deploy PHP App

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    name: 🏗️ Build & 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 🐘 Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3" # Cambia a tu versión de PHP
          extensions: mbstring, xml, ctype, iconv, pdo_mysql # Extensiones comunes

      - name: 🔍 Get Composer Cache Directory
        id: composer-cache-dir
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: 💾 Cache Composer packages
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: 📦 Install Dependencies
        run: composer install --no-dev --optimize-autoloader --no-interaction --no-progress

      - name: 📂 Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ./${{ secrets.SERVER_DIR }}/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/tests/**
            .gitignore
            README.md
            composer.json
            composer.lock
            phpunit.xml
            compose.yaml
            Containerfile
            Dockerfile
            .prettier*
            .vscode/
            .github/
            *.sql
            package.json
            package-lock.json
            .phpstorm.meta.php
            .editorconfig
            data/
